name: Build Custom Technorino

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.9.3"
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: >-
            qtimageformats
            qt5compat
          cache: true

      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          boost_version: "1.85.0"
          platform_version: "2022"
          toolset: msvc

      - name: Install OpenSSL
        run: choco install openssl --no-progress -y

      - name: Configure CMake
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCHATTERINO_PLUGINS=ON `
            -DBUILD_WITH_QTKEYCHAIN=OFF `
            -DCHATTERINO_LTO=OFF `
            -DBOOST_ROOT="${{ steps.install-boost.outputs.BOOST_ROOT }}" `
            -G "Ninja"

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Collect dependencies
        run: |
          mkdir artifact
          copy build\chatterino.exe artifact\
          windeployqt --release --no-translations artifact\chatterino.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Technorino-Custom-Windows
          path: artifact\
          retention-days: 30
