name: Build Custom Technorino

on:
  workflow_dispatch:

env:
  CONAN_VERSION: 2.28.1

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: Windows-QtCache-6.9.3-v2
          modules: qtimageformats
          version: "6.9.3"

      - name: Enable Developer Command Prompt
        uses: Chatterino/msvc-dev-cmd@v2.0.5
        with:
          arch: x64

      - name: Cache Conan packages
        uses: actions/cache@v5
        with:
          key: Windows-x64-conan-user-${{ hashFiles('**/conanfile.py') }}-QT6
          path: ~/.conan2/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Conan
        run: |
          pip install conan==${{ env.CONAN_VERSION }}
          conan --version
          conan profile detect -f
        shell: bash

      - name: Install dependencies via Conan
        run: |
          mkdir build
          cd build
          conan install .. \
            -s build_type=RelWithDebInfo \
            -c tools.cmake.cmaketoolchain:generator="Ninja" \
            -b missing \
            --output-folder=. \
            -o with_openssl3=True
          conan cache clean --source --build --download "*"
        shell: bash

      - name: Build
        shell: pwsh
        run: |
          cd build
          cmake `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo `
            -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" `
            -DUSE_PRECOMPILED_HEADERS=ON `
            -DCHATTERINO_LTO=OFF `
            -DCHATTERINO_PLUGINS=ON `
            -DBUILD_WITH_QTKEYCHAIN=OFF `
            -DFORCE_JSON_GENERATION=Off `
            ..
          ninja

      - name: Package
        shell: pwsh
        working-directory: build
        run: |
          windeployqt bin/chatterino.exe --release --no-compiler-runtime --no-translations --no-opengl-sw --dir Chatterino2/ --force-openssl
          cp bin/chatterino.exe Chatterino2/

      - name: Zip artifact
        shell: pwsh
        working-directory: build
        run: |
          7z a Technorino-Custom-Windows.zip Chatterino2/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Technorino-Custom-Windows
          path: build/Technorino-Custom-Windows.zip
          retention-days: 30
